[toolchain]
channel = "nightly"
components = [
  "rustc",
  "cargo",
  "clippy",
  "rustfmt",
  "rust-analyzer",
  "rust-src",
  "rust-std",
  "rust-docs",
  "miri",
]
profile = "default"

# components = ["llvm-tools"]
