rules:
  # template-injection:
  #   ignore:
  #     - ci.yml
  #     - ci-reusable.yml
  dangerous-triggers:
    ignore:
      - greetings.yml:3:1
  unpinned-uses:
    ignore:
      - release.yml
      - ci-reusable.yml
      - schedule-stale.yml
      - zizmor.yml
      - sync-labels.yml
      - lock.yml
      - gitguardian.yml
      - contributors.yml
      - codeql.yml
      - security.yml
      - security-reusable.yml
      - dependabot-update.yml
      - clean-owners.yml
  excessive-permissions:
    ignore:
      - zizmor.yml
      - sync-labels.yml
      - lock.yml
      - gitguardian.yml
      - release.yml
